# 24-AUG-2025
baseURL = 'https://maroph.github.io/nosense_hugo/'
DefaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'NoSense'
timeZone = 'Europe/Berlin'
#####publishDir = 'docs'
# Using theme as git submodule
# git submodule add https://github.com/halogenica/beautifulhugo themes/beautifulhugo
# https://raw.githubusercontent.com/halogenica/beautifulhugo/refs/heads/master/exampleSite/hugo.toml
theme = 'beautifulhugo'
pygmentsStyle = 'trac'
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = 'linenos=inline'
enableGitInfo = false
# enableGitInfo = true

[params]
  # homeTitle = 'NoSense Home Page'
  subtitle = 'Some of my stupid thoughts'
  # disclaimerText = 'First Draft Only'
  selfHosted = true
  mainSections = ['posts']
  favicon = 'images/favicon_hugo-32x32.png'
  logo = 'images/great_wave_off_kanagawa_200x200.jpg'
  # dateFormat = 'January 2, 2006'
  commit = false
  # commit = 'https://github.com/maroph/nosense_hugo/tree/'
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  hideAuthor = true
  [params.author]
    name = 'maroph'
    website = 'https://maroph.github.io/'
    # email = 'marochess@yahoo.com'
    github = 'maroph'
    mastodon = 'https://mastodon.social/@maroph'
    codepen = 'https://codepen.io/maroph/'
    # bluesky = 'maroph.bsky.social'

# https://gohugo.io/configuration/menus/
[menus]
  # [[menus.main]]
  #   name = 'Page'
  #   url = 'pages/page/'
  #   weight = 1
  [[menus.main]]
    name = 'Notes'
    pageRef = 'pages/notes'
    weight = 1
  [[menus.main]]
    parent = 'Notes'
    name = 'Note'
    url = 'pages/notes/note'
    weight = 1
  [[menus.main]]
    name = 'Bookmarks'
    pageRef = 'pages/bookmarks'
    weight = 2
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Adoptium'
    url = 'https://adoptium.net/'
    weight = 1
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Apache Tomcat'
    url = 'https://tomcat.apache.org/'
    weight = 2
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Git (windows)'
    url = 'https://git-scm.com/download/win'
    weight = 3
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Hugo'
    url = 'https://gohugo.io/'
    weight = 4
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Pandoc'
    url = 'https://pandoc.org/'
    weight = 5
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'OpenSSL'
    url = 'https://openssl-library.org/source/'
    weight = 6
  [[menus.main]]
    parent = 'Bookmarks'
    name = 'Zensical'
    url = 'https://zensical.org/'
    weight = 7
  [[menus.main]]
    name = 'Info'
    pageRef = 'pages/info'
    weight = 3
  [[menus.main]]
    parent = 'Info'
    name = 'About'
    url = 'pages/info/about/'
    # pageRef = 'pages/info/about.md'
    weight = 1
  [[menus.main]]
    parent = 'Info'
    name = 'Config'
    url = 'pages/info/config'
    weight = 2
  [[menus.main]]
    parent = 'Info'
    name = 'License'
    url = 'pages/info/license/'
    weight = 3
  [[menus.main]]
    parent = 'Info'
    name = 'Sitemap'
    url = '/sitemap.xml'
    weight = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.x]
    disable = true
  [privacy.youTube]
    disable = true

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

